### ISSUE TITLE
Node red 0.17.5 support

### ISSUE THREAD

**Issue by selfus** [johnty/node-red-contrib-i2clcd#1]
Hello,

Tried to follow [this guide.](https://nodered.org/docs/creating-nodes/packaging)
The node shows as installed, but I can't use it, as it doesn't appear in the pallete.

Can this be updated to work with the new red version? And be included in the flows page?

Thanks

**Comment by johnty** [comment]
Will try it out on a recent version and let you know! I did have to manually add the i2c dependency, iirc.

**Comment by selfus** [comment]
I will test it out as soon as you have something.

Thank you very much. Maybe I will learn some node.js so I can give you a hand later on.

**Comment by selfus** [comment]
Well, the dependency was missing. Thanks!
